Listen to maintenance events for interfaces
kytos-ng/topology pull request #13
Opened 2021-07-29 17:50 UTC by ajoaoff

Fixes #8 

Description of the change
=================

Topology was only listening to maintenance events for switches or links. 
This PR implements listeners for maintenances involving interfaces, generating corresponding
link up/down events.

Verification process
=============

Unit tests for this change were implemented and all the other tests passed.

2021-08-04 14:07 UTC, italovalcy approved these changes

2021-08-04 17:54 UTC, rmotitsuki requested changes

2021-08-04 17:54 UTC, rmotitsuki commented on main.py
> +            maintenance_uni.interface.enable()
I think that the interface state should be saved. If it was in the disabled state before the maintenance it must remain disabled.

2021-08-04 17:54 UTC, rmotitsuki commented on main.py
> +            self.handle_link_up(maintenance_uni.interface)
If the interface is not active before the maintenance, it will be activated in the handle_link_up.

2021-12-07 09:40 UTC, italovalcy approved these changes
Looks good to me. Great work for this PR, @ajoaoff, congratulations. I've just registered issue [maintenance#28](https://github.com/kytos-ng/maintenance/issues/28), so we can address the persistency of interface state if kytos gets restarted during a MW.

2022-05-24 17:22 UTC, viniarck commented
@ajoaoff I've just marked it as a draft since there are some dependencies/threads open

2023-05-16 19:45 UTC, viniarck commented
@ajoaoff thanks for this PR, I'll go ahead and close it, since the new `maintenance` blueprint that @Ktmi has specified will cover it and things have evolved. @Ktmi as your PRs start to land you can also close this original linked issue #8.

2023-05-16 19:45 UTC, closed without merging